### ISSUE TITLE
Activating SublimeHaskell only when .hs files are opened

### ISSUE THREAD

**Issue by jaxuru** [SublimeHaskell/SublimeHaskell#274]
Feature Request: One of the reasons SublimeText is so nice to use is how lightweight it is, supplying only what you need. Because of this, it feels a bit clunky to open sublime for something simple and non-haskell-related, like throwing together a script or something, and seeing that huge usage spike as Sublime Haskell inspects the database. It would be nice to have a preference option for ensuring Sublime Haskell only runs when a .hs file, or a folder/project with a .cabal file, is opened. I find myself disabling Sublime Haskell and only turning it on when I need it, which is awkward.

**Comment by YLiLarry** [comment]
Second this. I find that Sublime Haskell keeps reporting "Sublime Haskell: hsdev ping: no pong" in the console even when I'm writing C code. Is there a way to only enable it for Haskell code?

**Comment by iamrecursion** [comment]
I've been manually disabling and enabling it, but it's frightfully clunky to do so.

**Comment by jonaprieto** [comment]
Yes!, Sublime turns so slow, and in at some point, I'd closed it after disabling the package, and everything comes normally when I open again the next time.

**Comment by mvoidex** [comment]
Sry guys, have no time
I agree, it is annoying

**Comment by bscottm** [comment]
@jaxuru, @YLiLarry, @iamrecursion, @jonaprieto: I'll look into it in the near future.

**Comment by iamrecursion** [comment]
Excellent to hear! Your half-open pipe fix has fixed a not just one (as I said on Haskell-Cafe), but two of the issues I've been having.

**Comment by bscottm** [comment]
@iamrecursion: Thanks for the hat tip! It's going to take a bit of refactoring. Demand loading is actually implemented, but the code needs to be moved around. ST loads the plugin source in alphabetical order and the current demand loading is embedded in `autocomplete.py` (one of the first files loaded.)

**Comment by iamrecursion** [comment]
Looking forward to it! I'd offer to help if I had more free time, but not at the moment. I hope it goes smoothly for you!

**Comment by xldenis** [comment]
This would be nice, `hsdev` currently takes up 500mb as soon as I open sublime, even if I'm just writing text or editing a different language. Ensuring that `SublimeHaskell` no-ops until a haskell file loads would be greatly appreciated.

**Comment by bscottm** [comment]
@xldenis: `hsdev` should not get fired up until you load Haskell source into ST3. So, if you have a `.hs` file open, SublimeHaskell will fire up `hsdev`.

Let me get past the current release (and refactoring issues). I was working on startup refactoring, but then this whole problem of builds "hanging" and other minor issues came up. :-)

**Comment by xldenis** [comment]
![image](https://cloud.githubusercontent.com/assets/451373/24559823/be7c73d4-1605-11e7-83cb-652d945ec4f1.png)

`hsdev` booted up on sublime start, even when I only have ruby code open.

**Comment by bscottm** [comment]
@jaxuru, @YLiLarry, @iamrecursion, @jonaprieto, @mvoidex, @dabro:

Quick progress update: Getting very close to having this enhancement working, probably within the next two weeks or so. I had to refactor backend management in SublimeHaskell, which, as you can imagine, is non-trivial.

I'm at a point at which beta testing will be useful, if you're willing the help and you use `hsdev` as your backend. There is also a `none` backend, which should be self-explanatory. You will also have to change your ST user preferences -- `enable_hsdev`, `enable_ghc_mod` and related preferences are now gone, replaced with:

```yaml
    "backends": {
        "Local hsdev": {
            "default": true,
            "backend": "hsdev",
            "options": {
              "local": true,
              "port": 4567
            }
        },
        "Remote hsdev@localhost:4567": {
            "default": false,
            "backend": "hsdev",
            "options": {
                "local": false,
                "host": "localhost",
                "port": 4567
            }
        },
        "No backend": {
            "default": false,
            "backend": "none"
        }
    },
```

I do need to write the code so that you can change backends "on-the-fly" (e.g., stop `hsdev` and choose the `none` backend.)
