### ISSUE TITLE
Default stack target

### ISSUE THREAD

**Issue by noxecane** [SublimeHaskell/SublimeHaskell#439]
This is most probably a question but is there any way to select the target `SublimeHaskell` will build with stack. I have this situation

```yaml
library:
  source-dirs: src
  exposed-modules:
    - Lib

executables:
  dev:
    source-dirs: app
    main:        Main.hs
    dependencies:
      - maps-api
  
  prod:
    source-dirs: app
    main:        Main.hs
    dependencies:
      - maps-api
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
```

At first `SublimeHaskell` didn't work(no backend was selected) until I commented out the prod target(I could only do this because I had faced the same issue with `vscode` and `haskero`)
